### ISSUE TITLE
ChatBot Error | QnA

### ISSUE THREAD

**Issue by ismailmohammed** [Microsoft/BuildAnIntelligentBot#8]
Hi,

I have followed all the steps given readme files. Everything is working as expected but after publishing chatbot to Azure i am getting below error when it hits QnA.
In file we have switch case right in default case we have written logic to hit the QnA there we are getting below error.

Please help me on this.

> The given key was not present in the dictionary. - at System.ThrowHelper.ThrowKeyNotFoundException()
> at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
> at ChatBot.EchoWithCounterBot.<OnTurnAsync>d__17.MoveNext() in D:\RND\ChatBotRND\buildanintelligentbot\src\ChatBot\EchoWithCounterBot.cs:line 183
> — End of stack trace from previous location where exception was thrown —
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at ChatBot.Middlewares.TranslatorSpeechMiddleware.<OnTurnAsync>d__7.MoveNext() in D:\RND\ChatBotRND\buildanintelligentbot\src\ChatBot\Middlewares\TranslatorSpeechMiddleware.cs:line 77
> — End of stack trace from previous location where exception was thrown —
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at ChatBot.Middlewares.PersonalityChatMiddleware.<OnTurnAsync>d__3.MoveNext() in D:\RND\ChatBotRND\buildanintelligentbot\src\ChatBot\Middlewares\PersonalityChatMiddleware.cs:line 48
> — End of stack trace from previous location where exception was thrown —
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Bot.Builder.MiddlewareSet.<ReceiveActivityWithStatusAsync>d__3.MoveNext()
> — End of stack trace from previous location where exception was thrown —
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Bot.Builder.BotAdapter.<RunPipelineAsync>d__13.MoveNext()

**Comment by gsegares** [comment]
Hi, this is caused by an encryption issue during the local setup and the keys in the deployment. We addressed this problem in the new repository https://github.com/Microsoft/ailab/tree/master/BuildAnIntelligentBot
